name: Create Attestations

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write
            attestations: write

        steps:
            - name: Checkout
              uses: actions/checkout@v7
            
            - name: Generate main.js attestation
              uses: actions/attest@v4
              with:
                  subject-path: main.js
                  
            - name: Generate manifest.json attestation
              uses: actions/attest@v4
              with:
                  subject-path: manifest.json
                  
            - name: Generate styles.css attestation
              uses: actions/attest@v4
              with:
                  subject-path: styles.css


                  
                      
                      
